# Jogo dos 8
### Método de busca cega: Busca em Profundidade

In [1]:
import numpy as np
import time

### Metódo buscaEmProfundidade



In [36]:
def encontraEstadoAtual(matriz):
    # entrada: matriz 
    # saída: coordenada na matriz do item de valor 0
    result = np.where(matriz == 0)
    estado_atual = (result[0].item(0), result[1].item(0))
    
    return estado_atual

In [37]:
def encontraSucessores(matriz, estado_atual):
    sucessores = []
    direcoes = [[1, 1], [1, -1], [0, 1], [0, -1]]
    
    for direcao in direcoes:
        matriz_sucessora = np.copy(matriz)
        
        if direcao[0] == 1: # movimentações na vertical
            estado_trocado = (estado_atual[0], estado_atual[1] + direcao[1])
        else: # movimentações na horizontal
            estado_trocado = (estado_atual[0] + direcao[1], estado_atual[1])

        if estado_trocado[direcao[0]] >= 0 and estado_trocado[direcao[0]] < 3: 
            matriz_sucessora[estado_atual] = matriz[estado_trocado]
            matriz_sucessora[estado_trocado] = 0
            sucessores.append(matriz_sucessora)
            
    return sucessores

In [38]:
def verificaSeFoiVisitado(matriz, estados_visitados):
    for estado in estados_visitados:
        if (matriz == estado).all():
            return True
        
    return False

In [39]:
def acharProximoSucessorNaoVisitado(estados_visitados, estados_com_sucessores_nv, sucessores, index_atual):
    while len(sucessores) > index_atual + 1:
        ja_visitado = False
        for estado in estados_visitados:
            if (sucessores[index_atual + 1] == estado).all(): 
                ja_visitado = True
        
        if ja_visitado:
            index_atual += 1
        else:
            return sucessores[index_atual + 1]
    
    estado = estados_com_sucessores_nv[-1]
    estado_com_sucessores_nao_visitados = estados_com_sucessores_nv.copy()
    estado_com_sucessores_nao_visitados.pop()
    
    sucessores_estado = encontraSucessores(estado, encontraEstadoAtual(estado)) 
    return acharProximoSucessorNaoVisitado(estados_visitados, estado_com_sucessores_nao_visitados, sucessores_estado, 0)

In [64]:
def buscaEmProfundidade(matriz, matriz_objetivo, estados_visitados): 
    global iteracao
    if (matriz == matriz_objetivo).all():
        return True, matriz
    elif iteracao == 2000: 
        return False, matriz
    else:
        sucessores = encontraSucessores(matriz, encontraEstadoAtual(matriz))
        for sucessor in sucessores: 
            if iteracao <= 2000:
                if not verificaSeFoiVisitado(sucessor, estados_visitados):
                    iteracao += 1
                    return buscaEmProfundidade(sucessor, matriz_objetivo, estados_visitados + [sucessor])
                else:
                    try:
                        sucessor_valido = acharProximoSucessorNaoVisitado(estados_visitados, estados_visitados, sucessores, sucessores.index(sucessor))
                        iteracao += 1
                        return buscaEmProfundidade(sucessor_valido, matriz_objetivo, estados_visitados + [sucessor_valido])
                    except RecursionError:
                        print('Não foi possível encontrar a matriz desejada após ' + str(iteracao) + ' iterações - recursão excedida.')

In [65]:
def executar(matriz_entrada, matriz_objetivo):
    inicio = time.time()
    retorno, matriz_final = buscaEmProfundidade(matriz_entrada, matriz_objetivo, [])
    fim = time.time()

    print('------------------------------------------------------------------------------------')
    print('Matriz de entrada: ')
    print(matriz_entrada)
    print('------------------------------------------------------------------------------------')
    print('Matriz desejada: ')
    print(matriz_objetivo)
    print('------------------------------------------------------------------------------------')
    print('Matriz final: ')
    print(matriz_final)
    print('------------------------------------------------------------------------------------')
    
    if retorno:
        print('Foi possível encontrar a matriz desejada após ' + str(iteracao) + ' iterações.')
    else:
        print('Não foi possível encontrar a matriz desejada após ' + str(iteracao) + ' iterações.')

    print('A execução da busca em profundidade foi feita em ' + str(fim - inicio) + ' segundos.')
    print('------------------------------------------------------------------------------------')

In [66]:
matriz_objetivo = np.matrix('1 2 3; 4 5 6; 7 8 0')

entradas = []
entradas.append(np.matrix('1 2 3; 4 0 6; 7 5 8'))
entradas.append(np.matrix('1 2 3; 4 5 6; 7 0 8'))
entradas.append(np.matrix('0 2 3; 1 5 6; 7 4 8'))
entradas.append(np.random.choice(range(9), size=(3, 3), replace=False)) # matriz aleatória

for entrada in entradas:
    iteracao = 0
    executar(entrada, matriz_objetivo)

------------------------------------------------------------------------------------
Matriz de entrada: 
[[1 2 3]
 [4 0 6]
 [7 5 8]]
------------------------------------------------------------------------------------
Matriz desejada: 
[[1 2 3]
 [4 5 6]
 [7 8 0]]
------------------------------------------------------------------------------------
Matriz final: 
[[1 2 3]
 [4 5 6]
 [7 8 0]]
------------------------------------------------------------------------------------
Foi possível encontrar a matriz desejada após 915 iterações.
A execução da busca em profundidade foi feita em 6.854299783706665 segundos.
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
Matriz de entrada: 
[[1 2 3]
 [4 5 6]
 [7 0 8]]
------------------------------------------------------------------------------------
Matriz desejada: 
[[1 2 3]
 [4 5 6]
 [7 8 0]]
------------------------------------