In [1]:
from ipynb.fs.full.notebookDFS import *
from ipynb.fs.full.notebookGulosa import *
import numpy as np
import os

### Metódo limparOutputs
O método encontra as coordenadas do valor 0 na matriz passada por parâmetro.

In [2]:
def limparOutputs():
    if os.path.exists('./resultados_DFS.txt'):
        os.remove('./resultados_DFS.txt')
    
    if os.path.exists('./resultados_Gulosa.txt'):
        os.remove('./resultados_Gulosa.txt')
    
    print("Outputs limpos com sucesso!")
    print("-----------------------------------------------------------------------------------")

### Metódo dividirLista
Manipula os dados dos arquivos textos para análise.

In [3]:
def dividirLista(resultado):
    lista = []
    for linha in resultado:
        lista.append(linha.split(';'))
    return lista

### Metódo menorTempo
O método verifica o método de busca com o menor tempo para determinada matriz.

In [4]:
def menorTempo(opcoes):
    menor = []
    menor.append(opcoes[0])
    for op in opcoes:
        if menor[0][2] == op[2] and menor[0][0] != op[0]:
            menor.append(op)
        elif menor[0][2] > op[2]:
            menor = []
            menor.append(op)
    
    return menor

### Metódo menorIteracao
O método verifica o método de busca com o menor número de iterações para determinada matriz.

In [5]:
def menorIteracao(opcoes):
    menor = []
    menor.append(opcoes[0])
    for op in opcoes:
        if menor[0][3] == op[3] and menor[0][0] != op[0]:
            menor.append(op)
        elif menor[0][3] > op[3]:
            menor = []
            menor.append(op)
    
    return menor

### Metódo metodosExistentes
O método retorna o nome do método de busca a partir do identificador.

In [6]:
def metodosExistentes(opcoes):
    metodos = []
    for op in opcoes:
        identificador = int(op[0])
        if identificador == 0:
            metodos.append('Busca em profundidade')
        elif identificador == 1:
            metodos.append('Heurística Gulosa com critério Distância Euclidiana')
        elif identificador == 2:
            metodos.append('Heurística Gulosa com critério Pontos Diferentes')
        elif identificador == 3:
            metodos.append('Heurística Gulosa com critério Manhattan Distance')

    return metodos

### Metódo foiPossivelResolucao
O método verifica os métodos de busca que encontraram a matriz objetivo (com até 2000 iterações).

In [7]:
def foiPossivelResolucao(opcoes):
    possivel = []
    for op in opcoes:
        if op[1] == 'True':
            possivel.append(op)
            
    return possivel

### Metódo compararMetodos
O método lê os arquivos com os resultados das buscas e verifica os métodos de busca, mostrando o com menor tempo e menor número de iterações.

In [8]:
def compararMetodos():
    with open('resultados_DFS.txt') as f1, open('resultados_Gulosa.txt') as f2:
        resultadosDFS = f1.read().split('*') 
        resultadosGulosa = f2.read().split('*')

    resultadosGulosa = dividirLista(resultadosGulosa)
    resultadosDFS = dividirLista(resultadosDFS)

    for i in range(len(resultadosDFS) - 1):
        num = 2*i
        print("-----------------------------------------------------------------------------------")
        print("Matriz inicial: ")
        print(resultadosDFS[i][4])
        possivelResolucao = foiPossivelResolucao([resultadosDFS[i], resultadosGulosa[i + num], resultadosGulosa[i + num + 1], resultadosGulosa[i + num + 2]])

        if len(possivelResolucao) > 0:
            
            tempo = menorTempo(possivelResolucao)
            metodo = metodosExistentes(tempo)
            print("\nEm relação ao tempo, método(s) com o(s) menor(es): " + tempo[0][2] + ' segundos')
            for m in metodo: 
                print(m)
                
            iteracao = menorIteracao(possivelResolucao)
            metodo = metodosExistentes(iteracao)
            print("\nEm relação ao número de iterações, método(s) com o(s) menor(es): " + iteracao[0][3] + ' iterações')
            for m in metodo: 
                print(m)
                
            print("-----------------------------------------------------------------------------------")
        else: 
            print("\nNenhum dos métodos de busca chegaram à matriz objetivo com menos de 2000 iterações.")
            print("-----------------------------------------------------------------------------------")

### Método executarMetodosBuscas

O método executa as buscas informada (Heurística Gulosa - notebookGulosa) e não informada (Busca em Profundidade - notebookDFS).

In [9]:
def executarMetodosBuscas(entradas, matriz_objetivo):
    for entrada in entradas:
        iteracao = 0
        executarDFS(entrada, matriz_objetivo) # executa busca em profundidade
        executarGulosa(entrada, matriz_objetivo) # executa heurística gulosa
    
    print("Buscas com matriz objetivo executadas com sucesso!")
    print(matriz_objetivo)
    print("-----------------------------------------------------------------------------------")

## Execução com entradas estáticas

O método limpa os outputs, executa as buscas informada (Heurística Gulosa - notebookGulosa) e não informada (Busca em Profundidade - notebookDFS), e compara os resultados e identifica - para cada matriz - a(s) execução(ões) com menor tempo e menor número de iterações. 

In [10]:
limparOutputs()

matriz_objetivo_1 = np.matrix('1 2 3; 8 0 4; 7 6 5')
entradas_1 = []
entradas_1.append(np.matrix('2 0 3; 1 7 4; 6 8 5'))
entradas_1.append(np.matrix('0 1 2; 7 8 3; 6 5 4'))
entradas_1.append(np.matrix('2 8 3; 1 6 4; 7 0 5'))
entradas_1.append(np.matrix('0 2 3; 1 5 6; 7 4 8'))

executarMetodosBuscas(entradas_1, matriz_objetivo_1)

compararMetodos()

limparOutputs()

matriz_objetivo_2 = np.matrix('1 2 3; 4 5 6; 7 8 0')
entradas_2 = []
entradas_2.append(np.matrix('1 2 3; 4 0 6; 7 5 8'))
entradas_2.append(np.matrix('1 2 3; 4 5 6; 7 0 8'))
entradas_2.append(np.matrix('0 2 3; 1 4 5; 7 8 6'))
entradas_2.append(np.random.choice(range(9), size=(3, 3), replace=False)) 

executarMetodosBuscas(entradas_2, matriz_objetivo_2)

compararMetodos()

Outputs limpos com sucesso!
-----------------------------------------------------------------------------------
Buscas com matriz objetivo executadas com sucesso!
[[1 2 3]
 [8 0 4]
 [7 6 5]]
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
Matriz inicial: 
[[2 0 3]
 [1 7 4]
 [6 8 5]]

Em relação ao tempo, método(s) com o(s) menor(es): 0.0010101795196533203 segundos
Heurística Gulosa com critério Pontos Diferentes

Em relação ao número de iterações, método(s) com o(s) menor(es): 7 iterações
Heurística Gulosa com critério Distância Euclidiana
Heurística Gulosa com critério Pontos Diferentes
Heurística Gulosa com critério Manhattan Distance
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
Matriz inicial: 
[[0 1 2]
 [7 8 3]
 [6 5 4]]

Em relação ao tempo, 

## Execução com matriz de entrada pelo usuário

Usuário deve inserir, seguindo modelo do exemplo da inserção, a matriz 3x3 com números únicos de 0 a 8.


In [ ]:
print('Exemplo de inserção: 1 2 3; 4 0 6; 7 5 8')
print('Matriz resultante da inserção exemplo: ')
print(np.matrix('1 2 3; 4 0 6; 7 5 8'))
matriz = input('Insira números de 0 a 8 a serem inserios em uma matriz 3x3 como matriz de entrada, como o exemplo: ')
entrada = []
entrada.append(np.matrix(matriz))
matriz_objetivo = np.matrix('1 2 3; 4 5 6; 7 8 0')
    
print("-----------------------------------------------------------------------------------")
print('Matriz objetivo: ')
print(np.matrix('1 2 3; 4 5 6; 7 8 0'))
print("-----------------------------------------------------------------------------------")

limparOutputs()
executarMetodosBuscas(entrada, matriz_objetivo)
compararMetodos()    